### ISSUE TITLE
增加 Apple Music 安卓端的支持

### ISSUE THREAD

**Issue by haohaostudio** [577fkj/MIUIStatusBarLyric#109]
**环境信息**

模块版本: 3.43.19
MIUI版本: 12.5 21.12.8
Android版本:  12
屏幕类型: 小米10

**在最新的release版本中能否复现**
否

**Comment by 577fkj** [comment]
> **环境信息**
> 
> 模块版本: 3.43.19 MIUI版本: 12.5 21.12.8 Android版本: 12 屏幕类型: 小米10
> 
> **在最新的release版本中能否复现** 否

使用扩展
