### ISSUE TITLE
QQ 音乐 11.0.1.6 无法使用

### ISSUE THREAD

**Issue by StarWishsama** [577fkj/MIUIStatusBarLyric#110]
Android 12 ArrowOS
LSPosed 版本 1.6.5 (6272)
状态栏歌词 3.43.19

Log 如下

> [ 2021-12-22T23:39:14.133    10233: 10539: 11409 I/LSPosed-Bridge  ] 状态栏歌词： Notification(channel=com_tencent_qqmusic_player shortcut=null contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x300006a color=0x00000000 category=transport groupKey=PLAYER_NOTIFICATION_GROUP actions=5 vis=PUBLIC)
[ 2021-12-22T23:39:14.133    10233: 10539: 11409 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Context.sendBroadcast(android.content.Intent)' on a null object reference
	at d.a.a.d.g.i(Unknown Source:31)
	at d.a.a.c.o.beforeHookedMethod(:4)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.notify(Unknown Source:18)
	at com.tencent.qqmusicplayerprocess.servicenew.e.b(SourceFile:933)
	at com.tencent.qqmusicplayerprocess.servicenew.e.a(SourceFile:68)
	at com.tencent.qqmusicplayerprocess.servicenew.e$a.handleMessage(SourceFile:1013)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by xiaowine** [comment]
> Android 12 ArrowOS LSPosed 版本 1.6.5 (6272) 状态栏歌词 3.43.19
> 
> Log 如下
> 
> > [ 2021-12-22T23:39:14.133    10233: 10539: 11409 I/LSPosed-Bridge  ] 状态栏歌词： Notification(channel=com_tencent_qqmusic_player shortcut=null contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x300006a color=0x00000000 category=transport groupKey=PLAYER_NOTIFICATION_GROUP actions=5 vis=PUBLIC)
> > [ 2021-12-22T23:39:14.133    10233: 10539: 11409 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Context.sendBroadcast(android.content.Intent)' on a null object reference
> > at d.a.a.d.g.i(Unknown Source:31)
> > at d.a.a.c.o.beforeHookedMethod(:4)
> > at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
> > at LspHooker_.notify(Unknown Source:18)
> > at com.tencent.qqmusicplayerprocess.servicenew.e.b(SourceFile:933)
> > at com.tencent.qqmusicplayerprocess.servicenew.e.a(SourceFile:68)
> > at com.tencent.qqmusicplayerprocess.servicenew.e$a.handleMessage(SourceFile:1013)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loopOnce(Looper.java:201)
> > at android.os.Looper.loop(Looper.java:288)
> > at android.os.HandlerThread.run(HandlerThread.java:67)

系统问题，非模块问题。请更新系统
