### ISSUE TITLE
64位版本的网易云音乐无法使用

### ISSUE THREAD

**Issue by lvzhenbo** [577fkj/MIUIStatusBarLyric#117]
最近那小米应用商店更新了网易云，软件变成64位版本了，然后这个模块就失效了

**Comment by xiaowine** [comment]
> 最近那小米应用商店更新了网易云，软件变成64位版本了，然后这个模块就失效了

实测并没有问题

**Comment by lvzhenbo** [comment]
没事了，我重装应用和模块加上重启系统，这一套连招下来，莫名其妙就好了
